=== jpcluff/final_project/schema_alfDb.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "alienValidated": {
          "type": "boolean"
        },
        "addedDate": {
          "type": "string",
          "format": "date-time"
        },
        "creatorObj": {
          "type": "object",
          "properties": {
            "creators": {
              "type": "string"
            },
            "validated": {
              "type": "boolean"
            },
            "validatedDate": {
              "type": "string",
              "format": "date-time"
            }
          },
          "required": [
            "creators",
            "validated"
          ]
        },
        "summaryObj": {
          "type": "object",
          "properties": {
            "summary": {
              "type": "string"
            },
            "validated": {
              "type": "boolean"
            },
            "validatedDate": {
              "type": "string",
              "format": "date-time" 
            }
          },
          "required": [
            "summary",
            "validated"
          ]
        },
        "imagesArray": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "imageObj": {
                "type": "object",
                "properties": {
                  "addSequence": {
                    "type": "number",
                    "Minimum":0     
                  },
                  "imageSrc": {
                    "type": "string"      
                  },
                  "validated": {
                    "type": "boolean"      
                  },
                  "validatedDate": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "issuesReportedArray": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "issue": {
                          "type": "string"
                        },
                        "reportedBy": {
                          "type": "string"
                        },
                        "reportedDate": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "issueObj": {
                          "type": "object",
                          "properties": {
                            "addSequence": {
                              "type": "number",
                              "Minimum":0
                            },
                            "issue": {
                              "type": "string"
                            },
                            "reportedBy": {
                              "type": "string"
                            },
                            "reportedDate": {
                              "type": "string",
                              "format": "date-time"
                            }
                          },
                          "required": [
                            "addSequence",
                            "issue",
                            "reportedBy",
                            "reportedDate"
                          ]
                        }
                      },
                      "required": []
                    }
                  }
                },
                "required": [
                  "addSequence",
                  "imageSrc",
                  "validated"
                ]
              }
            },
            "required": [
              "imageObj"
            ]
          }
        }
      },
      "required": [
        "name",
        "alienValidated",
        "summaryObj"
      ]
    }
  }

=== jpcluff/final_project/t_alienLifeformDb.json
[
    {
        "name": "The Thing",
        "alienValidated": true,
        "addedDate": "2024-09-23",
        "creatorObj": {
            "creators": "John Carpenter, Bill Lancaster",
            "validated": true,
            "validatedDate": "2024-09-23"
        },
        "summaryObj": {
            "summary": "A shape-shifting extraterrestrial organism that infiltrates an Antarctic research station, mimicking its human hosts and creating paranoia and terror among the survivors.",
            "validated": true,
            "validatedDate": "2024-09-23"
        },
        "imagesArray": [
            {
                "imageObj": {
                    "addSequence": 0,
                    "imageSrc": "./images/TheThing.png",
                    "validated": true,
                    "validatedDate": "2024-09-23",
                    "issuesReportedArray": [
                        {
                            "issue": "The image is incorrect.",
                            "reportedBy": "User123",
                            "reportedDate": "2024-09-23"
                        },
                        {
                            "issue": "The image is too small.",
                            "reportedBy": "User456",
                            "reportedDate": "2024-09-23"
                        }
                    ]
                }
            },
            {
                "imageObj": {
                    "addSequence": 1,
                    "imageSrc": "./images/TheThing.png",
                    "validated": true,
                    "validatedDate": "2024-09-23",
                    "issuesReportedArray": [
                        {
                            "issueObj": {
                                "addSequence": 0,
                                "issue": "The image is incorrect.",
                                "reportedBy": "User123",
                                "reportedDate": "2024-09-23"
                            }
                        },
                        {
                            "issueObj": {
                                "addSequence": 1,
                                "issue": "The image is too small.",
                                "reportedBy": "User456",
                                "reportedDate": "2024-09-23"
                            }
                        }
                    ]
                }
            }
        ]
    }
]
