=== jpcluff/final_project/server/schema_alienRefList.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Alien Ref Overview List",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "imgOverview": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "source",
        "summary",
        "imgOverview"
      ]
    }
  }

=== jpcluff/final_project/data/H_alienRefList.json
[{"name":"H'Harn","source":"Edmond Hamilton's Star Kings series","summary":"[citation needed]","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hacan","source":"Twilight Imperium","summary":"leonine traders[citation needed]","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Haggunenons","source":"The Hitchhiker's Guide to the Galaxy","summary":"According to the Guide, the Haggunenons \"have the most impatient chromosomes in the Galaxy. Whereas most species are content to evolve slowly and carefully over thousands of generations, discarding a prehensile toe here, [...] hazarding another nostril there, the Haggunenons would have done for Charles Darwin what a squadron of Arcturan Stunt Apples would have done for Sir Isaac Newton. Their genetic structure is based on the quadruple sterated octohelix....\" Their tendency to evolve almost instantaneously has the downside of discarding one deficiency for another.","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Halflings","source":"Dances in the Snow, Genome","summary":"","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Halfworlders","source":"Marvel Comics","summary":"A species of anthropomorphic animals created from being given experiments on Halfworld.","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hallessi","source":"Harry Turtledove's Worldwar series","summary":"A subject species of the Race. Singular \"Halless\".","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hallucinoids","source":"X-COM: Terror from the Deep","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Halosians","source":"Farscape","summary":"Humanoid","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hangi","source":"Farscape","summary":"Humanoid","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Hani","source":"C. J. Cherryh's Chanur novels","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hanshaks","source":"Ascendancy","summary":"","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Harammins","source":"The History of the Galaxy series)","summary":"","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hardcore Hill Midgets","source":"Bravest Warriors","summary":"They are found on the planet Zgraxxis.","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Harika","source":"Star Control 3","summary":"","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Harmonia","source":"The Sirens of Titan","summary":"flatworm-like","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Harvesters","source":"Independence Day","summary":"","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Haydonites","source":"Robotech","summary":"","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Headcrabs","source":"Half-Life","summary":"","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Headies","source":"Noon Universe","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Heechee","source":"Frederik Pohl","summary":"","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Helmacrons","source":"K. A. Applegate's Animorphs series (specifically books 24 and 42)","summary":"Microscopic aliens with two arms and four legs, they are fungible, transferring their mind to another individual when killed. They are egotistical and have technology that can shrink other species down to their size.","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Heptapods","source":"Arrival","summary":"Giant octopus-like aliens with seven limbs","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Herald","source":"Star Control 3","summary":"","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hermat","source":"Star Trek","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hi-Five Aliens","source":"Bravest Warriors","summary":"Characterized by long, single arm above their heads.","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Hidetoshi Dekisugi (Parallel Planet on the contrary)","source":"Doraemon","summary":"Humanoid who is the gender-swapped version of Hidetoshi Dekisugi","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hierarchy","source":"Universe at War","summary":"A collective race of alien species including tall grey-like humanoid aliens, genetically altered beings, and enslaved alien races including the Skinwalkers.","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Highbreed","source":"Ben 10: Alien Force","summary":"Humanoid","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"High Ones","source":"Elfquest","summary":"Humanoid","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Hiigarans","source":"Homeworld","summary":"Humanoid","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hirogen","source":"Star Trek","summary":"","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Hisa","source":"C. J. Cherryh's Alliance-Union universe","summary":"","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Hive, The","source":"Renegade Legion","summary":"Gained starfaring capability after stealing a Terran ship.","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Hivers","source":"Sword of the Stars","summary":"","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Hivers","source":"Traveller RPG","summary":"modified starfish","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hobos","source":"Invader Zim","summary":"Humanoid","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hoka","source":"Poul Anderson and Gordon R. Dickson","summary":"teddy-bears imitating human history","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Hoix","source":"Doctor Who and Torchwood.","summary":"Humanoid","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Hooloovoo","source":"The Hitchhiker's Guide to the Galaxy","summary":"super-intelligent shade of the colour blue","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hoofonoggles","source":"Froonga Planet","summary":"Ape-like reptilian carnivores","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hoon","source":"David Brin's Uplift Universe","summary":"","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Horda[broken anchor]","source":"Doctor Who","summary":"","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Hork-Bajir","source":"K. A. Applegate's Animorphs","summary":"Large, reptilian aliens with large blades at each of their joints and on their heads. Often referred to as 'salad mixers'. Usually peaceful, despite their appearance, as their blades were meant to be used for stripping bark off the very tall trees of their home world. Over 99% of the species has the mental capacity of a six-year-old human child, however, rarely one is of an intelligence on par with people like Albert Einstein, Isaac Newton and Stephen Hawking; such specimen are known as 'seers'","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Horta","source":"Star Trek","summary":"Silicon-based lifeforms","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hoshio (Tatsuya)","source":"Starman: Love in Earth","summary":"Humanoid","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Howlers","source":"Animorphs (specifically book 26, The Attack)","summary":"Artificial creatures with skin that looks like lava, a devastating scream attack, and a hive mind that allows them to share information and battle experience. Proficient in many forms of weaponry, the villain Crayak uses them to exterminate other species, designing them to view killing as a game... until they started kissing every sentient beings they saw.","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hrossa","source":"C. S. Lewis' Space Trilogy","summary":"Humanoid","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hrud","source":"Warhammer 40,000","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hugo","source":"Adventure Time: Distant Lands","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hunters (Lekgolo)","source":"Halo","summary":"Large creatures of immense strength and stature. They are made of hundreds if not thousands of worms formed together to make a single mind. Part of the Covenant Hierarchy.","imgOverview":"images/placeholderImg/1-alien.png"},{"name":"Hunters","source":"Star Trek","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Humma","source":"Star Frontiers","summary":"Marsupials, born female, change to male after giving birth.","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hur'q","source":"Star Trek","summary":"Humanoid","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Hutts","source":"Star Wars","summary":"","imgOverview":"images/placeholderImg/2-alien.png"},{"name":"Husnock","source":"Star Trek","summary":"","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hydrans","source":"Star Trek","summary":"Humanoid","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hydrogues","source":"Saga of the Seven Suns","summary":"Live in gas giants","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hykraius","source":"DC Comics' Legion of Super-Heroes","summary":"","imgOverview":"images/placeholderImg/3-alien.png"},{"name":"Hylar","source":"Twilight Imperium","summary":"large-brained and aquatic","imgOverview":"images/placeholderImg/4-alien.png"},{"name":"Hynerians","source":"Farscape","summary":"Slug-like. The Hynerian empire governs many worlds, some of which have humanoid inhabitants","imgOverview":"images/placeholderImg/3-alien.png"}]
