=== jpcluff/final_project/schema/schema_alienRefList.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Alien Ref Overview List",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "alienValidated": {
          "type": "boolean"
        },
        "creators": {
          "type": "string"
        },
        "sourceType": {
          "enum": ["book","film","tv","game","comic","other"]
        },
        "summary": {
          "type": "string"
        },
        "imgOverview": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "alienValidated",
        "summary",
        "imgOverview"
      ]
    }
  }

=== jpcluff/final_project/server/t_alienOverviewList.json
[
{
    "name": "The Thing",
    "alienValidated": false,
    "creators": "John Carpenter, Bill Lancaster",
    "summary": "A shape-shifting extraterrestrial organism that infiltrates an Antarctic research station, mimicking its human hosts and creating paranoia and terror among the survivors.",
    "imgOverview": "./images/TheThing-0.png"
}
]
